# Generated by Django 4.2.3 on 2023-07-30 11:13

import coach_me.bookings.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last Name')),
                ('picture', models.URLField(blank=True, default='https://img.freepik.com/premium-vector/colored-silhouette-man-s-head-isolated-white-background_764382-618.jpg', null=True)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('private_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('company', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
                ('consent_terms', models.BooleanField(default=False)),
                ('newsletter_subscription', models.BooleanField(blank=True, default=False, null=True)),
                ('is_lector', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_company_name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), coach_me.bookings.validators.validate_if_string_is_alphanumeric], verbose_name='Short Company name')),
                ('legal_company_name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('company_register_number', models.PositiveBigIntegerField(unique=True)),
                ('contact_person_names', models.CharField(max_length=30)),
                ('contact_person_role', models.CharField(max_length=15)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('company_domain', models.CharField(default=None, max_length=15)),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
