# Generated by Django 4.2.3 on 2023-07-23 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('picture', models.URLField(default='https://i.pinimg.com/originals/58/51/2e/58512eb4e598b5ea4e2414e3c115bef9.jpg')),
                ('date_of_birth', models.DateTimeField(blank=True, default=None, null=True)),
                ('corporate_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone', models.CharField(default='+359', max_length=10)),
                ('company', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
                ('consent_terms', models.BooleanField(default=False)),
                ('newsletter_subscription', models.BooleanField(default=False)),
            ],
        ),
    ]
