# Generated by Django 4.2.3 on 2023-07-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_bookinguserprofile_newsletter_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinguserprofile',
            old_name='corporate_email',
            new_name='private_email',
        ),
    ]
