# Generated by Django 4.2.3 on 2023-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_corporate_email_bookinguserprofile_private_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
