# Generated by Django 4.2.3 on 2023-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_person_phone',
            field=models.CharField(default=1234567890, max_length=13),
            preserve_default=False,
        ),
    ]
