# Generated by Django 4.2.3 on 2023-07-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_bookinguserprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
