# Generated by Django 4.2.3 on 2023-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_bookinguserprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='picture',
            field=models.URLField(default='static/images/missing-person.png'),
        ),
    ]
