# Generated by Django 4.2.3 on 2023-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_bookinguserprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='picture',
            field=models.URLField(blank=True, default='/static/images/missing-person.jpg', null=True),
        ),
    ]
