# Generated by Django 4.2.3 on 2023-07-23 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_bookinguserprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 23, 14, 54, 42, 201007, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
