# Generated by Django 4.2.3 on 2023-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_bookinguserprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1999-12-31', null=True),
        ),
    ]
