# Generated by Django 4.2.3 on 2023-07-25 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_bookinguserprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last Name'),
        ),
    ]
