# Generated by Django 4.2.3 on 2023-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_bookinguserprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='picture',
            field=models.URLField(blank=True, default='https://img.freepik.com/premium-vector/colored-silhouette-man-s-head-isolated-white-background_764382-618.jpg', null=True),
        ),
    ]
