# Generated by Django 4.2.3 on 2023-07-28 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_bookinguserprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_company_name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Short Company name')),
                ('legal_company_name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('company_register_number', models.PositiveBigIntegerField(unique=True)),
                ('contact_person_names', models.CharField(max_length=30)),
                ('contact_person_role', models.CharField(max_length=15)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('company_domain', models.CharField(default=None, max_length=30)),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
