# Generated by Django 4.2.3 on 2023-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguserprofile',
            name='is_lector',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
