# Generated by Django 4.2.3 on 2023-07-29 16:03

import coach_me.bookings.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_bookinguserprofile_is_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_domain',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_company_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), coach_me.bookings.validators.validate_if_string_is_alphanumeric], verbose_name='Short Company name'),
        ),
    ]
