# Generated by Django 4.2.3 on 2023-07-30 11:13

import coach_me.bookings.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectors', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.CharField(choices=[('09:00:00', '09:00:00'), ('10:00:00', '10:00:00'), ('11:00:00', '11:00:00'), ('12:00:00', '12:00:00'), ('13:00:00', '13:00:00'), ('14:00:00', '14:00:00'), ('15:00:00', '15:00:00'), ('16:00:00', '16:00:00'), ('17:00:00', '17:00:00'), ('18:00:00', '18:00:00')], max_length=8)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), coach_me.bookings.validators.validate_string_is_letters_only])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), coach_me.bookings.validators.validate_string_is_letters_and_hyphens_only])),
                ('phone', models.CharField(max_length=10, validators=[coach_me.bookings.validators.validate_phone_numbers_formatting])),
                ('company_name', models.CharField(max_length=200)),
                ('corporate_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('private_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Private email')),
                ('training_mode', models.CharField(choices=[('Live', 'Live'), ('Online', 'Online')], default='Online', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('amount_paid_online', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('certificate_code', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_scheduled', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_platforms', models.CharField(blank=True, max_length=30, null=True)),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trainings.training')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lectors.lector')),
            ],
        ),
    ]
