# Generated by Django 4.2.3 on 2023-08-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectors', '0006_alter_lector_slug'),
        ('trainings', '0004_alter_training_id'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainings.training'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lectors.lector'),
        ),
    ]
