# Generated by Django 4.2.3 on 2023-07-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
