# Generated by Django 4.2.3 on 2023-07-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='employee',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='corporate_email',
        ),
    ]
