# Generated by Django 4.2.3 on 2023-08-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booking_type_alter_booking_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_platforms',
            field=models.CharField(blank=True, choices=[('Teams', 'Teams'), ('Zoom', 'Zoom'), ('Skype', 'Skype'), ('Google meetings', 'Google meetings')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='training_mode',
            field=models.CharField(choices=[('Live', 'Live'), ('Online', 'Online')], default='Online', max_length=6),
        ),
    ]
