# Generated by Django 4.2.3 on 2023-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pvt_email',
            new_name='private_email',
        ),
        migrations.AddField(
            model_name='booking',
            name='corporate_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
