# Generated by Django 4.2.3 on 2023-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_email_booking_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='private_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Private email'),
        ),
    ]
