# Generated by Django 4.2.3 on 2023-07-30 11:13

import coach_me.bookings.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30, validators=[django.core.validators.MinLengthValidator(2), coach_me.bookings.validators.validate_string_is_letters_only])),
                ('last_name', models.CharField(default=None, max_length=30, validators=[django.core.validators.MinLengthValidator(2), coach_me.bookings.validators.validate_string_is_letters_and_hyphens_only])),
                ('phone', models.CharField(default=None, max_length=10, validators=[coach_me.bookings.validators.validate_phone_numbers_formatting])),
                ('email', models.EmailField(default=None, max_length=254)),
                ('lector_image', models.URLField(default='https://img.freepik.com/free-icon/user_318-159711.jpg')),
                ('biography', models.TextField()),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('service_integrity', models.ManyToManyField(to='trainings.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
