# Generated by Django 4.2.3 on 2023-08-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, unique=True),
        ),
    ]
