# Generated by Django 4.2.3 on 2023-07-23 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='short_company_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Short Company name'),
        ),
    ]
