# Generated by Django 4.2.3 on 2023-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinguser',
            name='groups',
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='groups',
            field=models.CharField(blank=True, choices=[('STAFF', 'STAFF'), ('LECTOR', 'LECTOR'), ('DEFAULT_USER', 'DEFAULT_USER')], default='DEFAULT_USER', max_length=12, null=True),
        ),
    ]
