# Generated by Django 4.2.3 on 2023-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='c_labels',
            field=models.CharField(blank=True, choices=[('COACHME_STAFF', 'COACHME_STAFF'), ('COACHME_LECTOR', 'COACHME_LECTOR'), ('COACHME_USER', 'COACHME_USER')], default='DEFAULT_USER', max_length=14, null=True, verbose_name='COACHME Groups'),
        ),
    ]
