# Generated by Django 4.2.3 on 2023-07-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_short_company_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinguser',
            managers=[
            ],
        ),
    ]
