# Generated by Django 4.2.3 on 2023-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_bookinguser_groups_bookinguser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguser',
            name='groups',
            field=models.CharField(blank=True, choices=[('COACHME_STAFF', 'COACHME_STAFF'), ('COACHME_LECTOR', 'COACHME_LECTOR'), ('COACHME_USER', 'COACHME_USER')], default='DEFAULT_USER', max_length=14, null=True),
        ),
    ]
