# Generated by Django 4.2.3 on 2023-07-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bookinguser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
